name: FSD CI

# 触发条件：当代码推送到 main 分支或创建拉取请求时触发
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# 定义作业
jobs:
  build:
    runs-on: ubuntu-latest  # 使用 GitHub 托管的 Ubuntu 环境

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 设置 CMake 环境
      - name: Set up CMake
        uses: actions/setup-cmake@v2

      # 3. 安装依赖（如果需要）
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      # 4. 创建构建目录并编译项目
      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      # 5. 运行测试（如果有测试用例）
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
